spring.application.name: spielplan


server.port: 7080

# H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2
h2.tcp.enabled: true
h2.tcp.port: 7090

# Datasource
spring.datasource:
  url: jdbc:h2:file:~/spielplan
  username: sa
  password:

spring.jackson.serialization:
  write-dates-as-timestamps: false

# Kafka
spring.kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Logging
logging.level.root: INFO
